.PHONY: all build cmake clean

BUILD_DIR := build
# Build type: Debug|Release
# By default = Debug
BUILD_TYPE ?= Debug

all: build

# Makefile generated by CMAKE
${BUILD_DIR}/Makefile:
    # -B: specify build directory where to store files/generate makefile
    # -D: cmake options when CMakeList.txt is evaluated
    #   - CMAKE_BUILD_DIR: where to put artifacts of the evaluation/buid
    #   - CMAKE_EXPORT_COMPILE_COMMANDS: export the compilation units compile
    #     commands in a file called "compile_commands.json" in the build directory
	cmake \
		-B${BUILD_DIR} \
		-DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
		-DCMAKE_EXPORT_COMPILE_COMMANDS=true 

cmake: ${BUILD_DIR}/Makefile

build: cmake
    # -C: change to BUILD_DIR directory
    # --no-print-directory: don't show the above directory change in the log
	$(MAKE) -C ${BUILD_DIR} --no-print-directory

#SRCS := $(shell find ./Core -name '*.[ch]' -or -name '*.[ch]pp')
#format: $(addsuffix .format,${SRCS})
#
#%.format: %
#	clang-format -i $<

clean:
	rm -rf -fR $(BUILD_DIR)
