/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Mon Jul  3 15:25:38 2023.
 */

#include <string.h>

#include "mcb.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

int mcb_tlb_battery_tsal_status_pack(
    uint8_t *dst_p,
    const struct mcb_tlb_battery_tsal_status_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->tsal_is_green_on, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->tsal_is_air_pos_closed, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->tsal_is_air_neg_closed, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->tsal_is_relay_precharge_closed, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->tsal_is_dc_bus_over60_v, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->intentional_state_air_pos, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->intentional_state_air_neg, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->intentional_state_relay_precharge, 7u, 0x80u);
    dst_p[1] |= pack_left_shift_u8(src_p->scs_short2_gnd_air_pos, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->scs_short2_gnd_air_neg, 1u, 0x02u);
    dst_p[1] |= pack_left_shift_u8(src_p->scs_is_any_short2_gnd_present, 2u, 0x04u);
    dst_p[1] |= pack_left_shift_u8(src_p->imp_is_any_imp_present, 3u, 0x08u);
    dst_p[1] |= pack_left_shift_u8(src_p->imp_is_air_pos_imp_present, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->imp_is_air_neg_imp_present, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->imp_is_relay_precharge_imp_present, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->imp_is_dc_bus_voltage_imp_present, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u8(src_p->imp_is_any_imp_latched, 0u, 0x01u);

    return (3);
}

int mcb_tlb_battery_tsal_status_unpack(
    struct mcb_tlb_battery_tsal_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->tsal_is_green_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->tsal_is_air_pos_closed = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->tsal_is_air_neg_closed = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->tsal_is_relay_precharge_closed = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->tsal_is_dc_bus_over60_v = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->intentional_state_air_pos = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->intentional_state_air_neg = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->intentional_state_relay_precharge = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    dst_p->scs_short2_gnd_air_pos = unpack_right_shift_u8(src_p[1], 0u, 0x01u);
    dst_p->scs_short2_gnd_air_neg = unpack_right_shift_u8(src_p[1], 1u, 0x02u);
    dst_p->scs_is_any_short2_gnd_present = unpack_right_shift_u8(src_p[1], 2u, 0x04u);
    dst_p->imp_is_any_imp_present = unpack_right_shift_u8(src_p[1], 3u, 0x08u);
    dst_p->imp_is_air_pos_imp_present = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->imp_is_air_neg_imp_present = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->imp_is_relay_precharge_imp_present = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->imp_is_dc_bus_voltage_imp_present = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->imp_is_any_imp_latched = unpack_right_shift_u8(src_p[2], 0u, 0x01u);

    return (0);
}

uint8_t mcb_tlb_battery_tsal_status_tsal_is_green_on_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_tsal_is_green_on_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_tsal_is_green_on_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_tsal_is_air_pos_closed_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_tsal_is_air_pos_closed_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_tsal_is_air_pos_closed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_tsal_is_air_neg_closed_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_tsal_is_air_neg_closed_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_tsal_is_air_neg_closed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_tsal_is_relay_precharge_closed_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_tsal_is_relay_precharge_closed_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_tsal_is_relay_precharge_closed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_tsal_is_dc_bus_over60_v_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_tsal_is_dc_bus_over60_v_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_tsal_is_dc_bus_over60_v_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_intentional_state_air_pos_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_intentional_state_air_pos_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_intentional_state_air_pos_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_intentional_state_air_neg_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_intentional_state_air_neg_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_intentional_state_air_neg_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_intentional_state_relay_precharge_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_intentional_state_relay_precharge_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_intentional_state_relay_precharge_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_scs_short2_gnd_air_pos_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_scs_short2_gnd_air_pos_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_scs_short2_gnd_air_pos_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_scs_short2_gnd_air_neg_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_scs_short2_gnd_air_neg_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_scs_short2_gnd_air_neg_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_scs_is_any_short2_gnd_present_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_scs_is_any_short2_gnd_present_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_scs_is_any_short2_gnd_present_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_imp_is_any_imp_present_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_imp_is_any_imp_present_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_imp_is_any_imp_present_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_imp_is_air_pos_imp_present_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_imp_is_air_pos_imp_present_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_imp_is_air_pos_imp_present_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_imp_is_air_neg_imp_present_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_imp_is_air_neg_imp_present_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_imp_is_air_neg_imp_present_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_imp_is_relay_precharge_imp_present_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_imp_is_relay_precharge_imp_present_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_imp_is_relay_precharge_imp_present_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_imp_is_dc_bus_voltage_imp_present_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_imp_is_dc_bus_voltage_imp_present_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_imp_is_dc_bus_voltage_imp_present_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_tsal_status_imp_is_any_imp_latched_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_tsal_status_imp_is_any_imp_latched_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_tsal_status_imp_is_any_imp_latched_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int mcb_tlb_battery_shut_status_pack(
    uint8_t *dst_p,
    const struct mcb_tlb_battery_shut_status_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->is_shut_closed_pre_ams_imd_latch, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->is_shut_closed_post_ams_latch, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->is_shut_closed_post_imd_latch, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->is_shutdown_closed_pre_tlb_batt_final, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->is_ams_error_latched, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->is_imd_error_latched, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->is_sd_prch_rly_closed, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->shutdown_adc_post_sd_precharge_relay, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->shutdown_adc_ai_rs_opening_delay_caps, 0u, 0xffu);

    return (3);
}

int mcb_tlb_battery_shut_status_unpack(
    struct mcb_tlb_battery_shut_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->is_shut_closed_pre_ams_imd_latch = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->is_shut_closed_post_ams_latch = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->is_shut_closed_post_imd_latch = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->is_shutdown_closed_pre_tlb_batt_final = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->is_ams_error_latched = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->is_imd_error_latched = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->is_sd_prch_rly_closed = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->shutdown_adc_post_sd_precharge_relay = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->shutdown_adc_ai_rs_opening_delay_caps = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

uint8_t mcb_tlb_battery_shut_status_is_shut_closed_pre_ams_imd_latch_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_shut_status_is_shut_closed_pre_ams_imd_latch_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_shut_status_is_shut_closed_pre_ams_imd_latch_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_shut_status_is_shut_closed_post_ams_latch_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_shut_status_is_shut_closed_post_ams_latch_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_shut_status_is_shut_closed_post_ams_latch_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_shut_status_is_shut_closed_post_imd_latch_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_shut_status_is_shut_closed_post_imd_latch_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_shut_status_is_shut_closed_post_imd_latch_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_shut_status_is_shutdown_closed_pre_tlb_batt_final_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_shut_status_is_shutdown_closed_pre_tlb_batt_final_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_shut_status_is_shutdown_closed_pre_tlb_batt_final_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_shut_status_is_ams_error_latched_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_shut_status_is_ams_error_latched_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_shut_status_is_ams_error_latched_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_shut_status_is_imd_error_latched_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_shut_status_is_imd_error_latched_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_shut_status_is_imd_error_latched_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_shut_status_is_sd_prch_rly_closed_encode(double value)
{
    return (uint8_t)(value);
}

double mcb_tlb_battery_shut_status_is_sd_prch_rly_closed_decode(uint8_t value)
{
    return ((double)value);
}

bool mcb_tlb_battery_shut_status_is_sd_prch_rly_closed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t mcb_tlb_battery_shut_status_shutdown_adc_post_sd_precharge_relay_encode(double value)
{
    return (uint8_t)(value / 0.117);
}

double mcb_tlb_battery_shut_status_shutdown_adc_post_sd_precharge_relay_decode(uint8_t value)
{
    return ((double)value * 0.117);
}

bool mcb_tlb_battery_shut_status_shutdown_adc_post_sd_precharge_relay_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t mcb_tlb_battery_shut_status_shutdown_adc_ai_rs_opening_delay_caps_encode(double value)
{
    return (uint8_t)(value / 0.117);
}

double mcb_tlb_battery_shut_status_shutdown_adc_ai_rs_opening_delay_caps_decode(uint8_t value)
{
    return ((double)value * 0.117);
}

bool mcb_tlb_battery_shut_status_shutdown_adc_ai_rs_opening_delay_caps_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}
